### PR TITLE
Benchmark improvements

### PR DESCRIPTION
**Pull request by akx**
I tried running the benchmarks on my macOS box, and they failed due to `sched_setaffinity` not being a thing.

Beyond that, I realized the benchmark test cases could use a bit of DRYing, so [`pytest.mark.parametrize`](https://docs.pytest.org/en/6.2.x/parametrize.html) to the rescue :)

### CODE REVIEW

**Comment by ijl** [comment]
Thanks. I agree with the changes on conditionaly setting affinity and using `lru_cache`. I think `pytest.mark.parametrize` introduces a small bias in consistently running everything orjson first and other libraries later. I'm not disabling boost to run these. Also `orjson_dumps` as a wrapper like other libraries else made the call overhead consistent--probably less with recent Python versions admittedly.

**Comment by akx** [comment]
Good point on the wrapper -- I overlooked it and can absolutely restore that.

With the number of iterations that `pytest-benchmark` runs anyway, would a bias in the run order of libraries truly matter? Of course I can make that `random.shuffle(libraries)` if you believe it matters...

**Comment by akx** [comment]
@ijl:

I restored the wrapper for the `orjson` calls.

I also added `pytest-random-order`; subsequent benchmark runs should thus cancel out any possible biases caused by run order.

What do you think?

**Comment by ijl** [comment]
Looks good, merged in d0016cdc29793f33c9f0842c3848822474d0dc4b, thanks.

**Pull request closed without merging**
