### PR TITLE
Call `__str__` for non-str dict keys in dumps

### LINKED ISSUE #40: Relax strict enforcing of keys type to string
I would like to use orjson for structlog, but as it turns out, people are dumping arbitrary data for debugging purposes, where you cannot ensure dict key types are always strings.

So I ask, if there is even a technical reason to enforce string keys and if not, if it is possible to optionally relax this constraint...?

### PR DESCRIPTION
**Pull request by svrakitin**
Closes #40. Maybe worth adding an option for this, but this will require migration from `u8` to `u16`+ for opts. Makes it possible to have duplicate keys as in standard library.

@ijl I also noticed that orjson.pyi is missing some opts from rust library.

### CODE REVIEW

**Comment by necaris** [comment]
Since as has been noted this [makes serialize / deserialize not perfect inverses](https://github.com/ijl/orjson/issues/40#issuecomment-585445730) this might be best guarded by an option?

**Comment by svrakitin** [comment]
@necaris I will follow up with an option. Thanks for feedback.

**Comment by ijl** [comment]
There are design questions still that I just posted about in #40. I think using `PyObject_Str` is generally not the way to go. E.g., this crashes if `__str__` returns `bytes` (realistic enough from projects that began in python2), if `__str__` is set to a literal (realistic in my experience), if `__str__` raises an exception (realistic in my experience).

**Comment by diefans** [comment]
@ijl https://docs.python.org/2/reference/datamodel.html#object.__str__ states clearly that 

>     The return value must be a string object.

and since https://docs.python.org/2/reference/datamodel.html#object.__repr__ states

> The return value must be a string object. If a class defines __repr__() but not __str__(), then __repr__() is also used when an “informal” string representation of instances of that class is required.

IMHO your argument of a possibly wrong API contract on behalf of unknown users should not stop this feature.

**Comment by diefans** [comment]
@necaris see pythons `json`:
```python
>>> import json
>>> a = {'abc': 'abc', 1:1, 1.1:1.1, True: True}
>>> assert json.loads(json.dumps(a)) == a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```

**Comment by necaris** [comment]
@diefans thank you for confirming what I was saying. Whereas if all keys are strings, they _are_ perfect inverses:
```python
>>> import json
>>> a = {"abc": "abc", "def": 123}
>>> assert json.loads(json.dumps(a)) == a
```

**Comment by danieltahara** [comment]
@svrakitin why is this closed?

**Comment by svrakitin** [comment]
@danieltahara I will reopen it when there is a decision on how this should be implemented. :)

**Pull request closed without merging**
