### PR TITLE
Added ability to serialize `decimal.Decimal` instances as `str`.

### PR DESCRIPTION
**Pull request by ermakov-oleg**
> Why not converts Decimal objects to floats? 

Often loss of precision is unacceptable, for example, when working with currency. 
So a reasonable default would be to serialize Decimal as a string.

@ijl What do you think about that?

### CODE REVIEW

**Comment by falkben** [comment]
There's a section in the Readme that shows how you can override the default behavior, and it even uses Decimal.

**Comment by ermakov-oleg** [comment]
@falkben This is true, but when using the override in "default", the serialization of Decimal is very slow (more than 20 times slower).

Also, this behavior is hidden behind a feature flag, so who doesn't need this behavior can simply not enable it.

**Comment by ijl** [comment]
If you or someone else wants to implement this, please specify how it will handle serializing as float64, how it will handle serializing as str (I see both preferences used), and ready-to-ship markdown documentation on both in https://github.com/ijl/orjson/issues/172. Those design issues need to be sorted out before looking at implementation, sorry @ermakov-oleg.

**Comment by tooptoop4** [comment]
@ermakov-oleg do u have a .whl with this?

**Pull request closed without merging**
