### PR TITLE
Add numpy primitives

### PR DESCRIPTION
**Pull request by aviramha**
Fix https://github.com/ijl/orjson/issues/109
It's my first take in the project, so there might be room for improvement. I wasn't sure if to use "safe" ways of interacting with Numpy objects (AsLong and such) or just defining the struct myself (which seems to be the way it was done already, so I went that path)
I also wasn't sure regarding the split of modules and etc.. I'll be glad to receive constructive CR.

### CODE REVIEW

**Comment by aviramha** [comment]
@ijl waiting for your CR :)

**Comment by ppd0705** [comment]
hope support  numpy type soon

**Comment by aviramha** [comment]
Any news?

**Comment by ijl** [comment]
I think the check for whether numpy exists should be done once. We can assume numpy will always be checked last and its branch can end with returning default as well. Consolidating them might suggest having a struct with all numpy type pointers and an option on that to indicate numpy is present. The amount added here to the main loop feels like a lot for an edge case of an optional feature and it may be better to have `NumpyScalar` and `NumpyArray` types or even just one `Numpy` type that is then checked again for its specific type. The extra check is negligible but it would keep the complexity out of the main loop and `ObType`. In any case I prefer if there is a numpy module that the numpy array code be there as well or else that's confusing. Please also apply `cargo fmt` and `./lint`.

**Comment by aviramha** [comment]
I hope I understood most of your concerns. The enum part is a bit lousy but so am I in rust :D

**Comment by ijl** [comment]
I squashed this and commited it to master as f11de5f2b4fe648d11f01f2d3249ccd8bd427623. Thanks for contributing it. To be released in 3.3.0.

**Pull request closed without merging**
