### PR TITLE
chore: improve stub for JSONDecodeError

### PR DESCRIPTION
**Pull request by PrettyWood**
When using `orjson.JSONDecodeError`, I faced a (small) issue to have both `mypy` (static type checking) and `pytest` (runtime) happy.

### Test 1
```py
import pytest
from pytest_mock import MockerFixture
import orjson


def test(mocker: MockerFixture) -> None:
    mocker.patch.object(
        orjson,
        "dumps",
        side_effect=orjson.JSONDecodeError
    )
    with pytest.raises(orjson.JSONDecodeError):
        orjson.dumps({"a": 1})
```
```console
▶ mypy test/test_jsondecodeerror.py
Success: no issues found in 1 source file
```
```console
▶ pytest test/test_jsondecodeerror.py
…
`TypeError: JSONDecodeError.__init__() missing 3 required positional arguments: 'msg', 'doc', and 'pos’`
```

### Test 2
```py
import pytest
from pytest_mock import MockerFixture
import orjson


def test(mocker: MockerFixture) -> None:
    mocker.patch.object(
        orjson,
        "dumps",
        side_effect=orjson.JSONDecodeError(msg="the_msg", doc="the_doc", pos=1)
    )
    with pytest.raises(orjson.JSONDecodeError):
        orjson.dumps({"a": 1})
```
```console
▶ mypy test/test_jsondecodeerror.py
test/test_jsondecodeerror.py:11: error: Unexpected keyword argument "msg" for "JSONDecodeError"
test/test_jsondecodeerror.py:11: error: Unexpected keyword argument "doc" for "JSONDecodeError"
test/test_jsondecodeerror.py:11: error: Unexpected keyword argument "pos" for "JSONDecodeError"
```
```console
▶ pytest test/test_jsondecodeerror.py
1 passed in 0.01s
```

This PR fixes this and should be closer to [the truth](https://github.com/ijl/orjson/blob/master/src/typeref.rs#L160-L164)

### CODE REVIEW

**Comment by ijl** [comment]
Ok, thanks for looking at this. Could you include the behavior you want in a regression test in integration/typestubs.py or the like? I can run mypy and pytest against it unless you'd like to add that to the runner.

**Comment by PrettyWood** [comment]
@ijl Thanks. Does https://github.com/ijl/orjson/pull/260/commits/07adbf01c98a0648495484c8a131fb22785e0ca8 work for you?

**Comment by ijl** [comment]
Yes,  and I just fixed it up to run on only one job and merged as 651b700115c2cdaf4e40cc94965f2834993def6f. Thank you.

**Comment by ijl** [comment]
https://github.com/ijl/orjson/releases/tag/3.7.1

**Pull request closed without merging**
